name: Octo Organization CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo $STAGING_ENV
  reuse:
    uses: casa-vega/.github/.github/workflows/reusable.yml@main
